# Generated by Django 5.1 on 2024-09-10 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='question_description',
        ),
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.CharField(default='Easy', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='question_name',
            field=models.CharField(default='Question_name', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.CharField(default='Math', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.CharField(default='Probability', max_length=30),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Poll',
        ),
    ]
