# Generated by Django 5.1.2 on 2024-10-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poll", "0005_test_questionattempt_teststat"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="completed",
            field=models.BooleanField(default=False, help_text="Is the test taken?"),
        ),
    ]
