# Generated by Django 5.1.2 on 2024-10-24 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("poll", "0006_test_completed"),
    ]

    operations = [
        migrations.RenameField(
            model_name="test",
            old_name="completed",
            new_name="done",
        ),
    ]
